[build-system]
requires = ["maturin>=0.1.0"]
build-backend = "maturin"

[project]
name = "pixdraft-engine"
version = "0.0.3"
requires-python = ">=3.9"

[tool.maturin]
features = ["pyo3/extension-module"]